version: '2.32.4'

services:
  db:
    container_name: postgres
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5435:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    container_name: redis
    image: redis:5.0
    restart: unless-stopped
    ports:
      - 6380:6379
    command: >
      sh -c '
       mkdir -p /usr/local/etc/redis &&
       echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
       echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
       echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
       echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
       echo "dir /data" >> /usr/local/etc/redis/redis.conf &&
       redis-server /usr/local/etc/redis/redis.conf
      '
    volumes:
      - redis_data:/data
    networks:
      - backend

volumes:
  postgres_data:
  redis_data:


networks:
  backend:
